// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcKap.Data;

#nullable disable

namespace MvcKap.Migrations
{
    [DbContext(typeof(MvcKapContext))]
    [Migration("20240924115502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcKap.Models.Calculations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EphedrineConc")
                        .HasColumnType("float");

                    b.Property<double>("FentanylConc")
                        .HasColumnType("float");

                    b.Property<double>("GlycopyrrolateConc")
                        .HasColumnType("float");

                    b.Property<double>("IvftBolusVolume")
                        .HasColumnType("float");

                    b.Property<double>("IvftRate")
                        .HasColumnType("float");

                    b.Property<double>("KetamineConc")
                        .HasColumnType("float");

                    b.Property<double>("TranexamicAcidConc")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("MvcKap.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Bcs")
                        .HasColumnType("int");

                    b.Property<double>("BodyWeight")
                        .HasColumnType("float");

                    b.Property<int>("BpDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("BpMean")
                        .HasColumnType("int");

                    b.Property<int>("BpSystolic")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<double>("LeanBodyWeight")
                        .HasColumnType("float");

                    b.Property<int>("RespRate")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
